# Gen postgre container
version: '3.1'

services:
  db:
    image: postgres:16.0
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - '5432:5432'
